DROP DATABASE IF EXISTS IFSP;

CREATE DATABASE IF NOT EXISTS IFSP;
USE IFSP;
CREATE TABLE Cidade (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100),
    estado CHAR(2)
);
CREATE TABLE Cliente(
id INT AUTO_INCREMENT,
nome VARCHAR(100),
email VARCHAR(100),
senha VARCHAR(100),
ativo VARCHAR(100),
cidade_id INT,
PRIMARY KEY(id),
CONSTRAINT FK_ClienteCidade
FOREIGN KEY(cidade_id)REFERENCES Cidade(id)
);